jwt:
  secret: your-super-long-random-secret-key-at-least-64-chars-2026

spring:
  application:
    name: nova-ai-chatbot-backend

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${YOUR_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash-lite
            temperature: 0.7