jwt:
  secret: your-super-long-random-secret-key-at-least-64-chars-2026

spring:
  application:
    name: nova-ai-chatbot-backend


  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/nova_ai_db
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${YOUR_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  # Gemini Configuration
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        model: gemini-2.5-flash-lite   # ← Yaha se model control karo
        temperature: 0.7
        max-output-tokens: 800